version: '3'

services:
  db:
    image: postgres
    container_name: postgres-capitual
    restart: always
    environment:
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_DB: "capitual_payment_service"
    ports:
      - "5432:5432"
  redis:
    image: redis
    container_name: redis-capitual
    restart: always
    ports:
      - "6379:6379"
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: microservice-capitual
    command: npm run dev
    ports:
      - "3000:3000"
    volumes:
      - .:/home/app
    depends_on:
      - db
      - redis

