# Set the version of docker compose to use
version: '3.9'

# The containers that compose the project
services:
  db:
    image: postgres:13
    restart: always
    container_name: db-tests-banking
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: banking-tests-db
  redis:
    image: redis
    container_name: redis-tests-banking
    restart: always
    ports:
      - "6379:6379"
